<?php
/*
 * Copyright (C) 2020 Paymentsense Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author      Paymentsense
 * @copyright   2020 Paymentsense Ltd.
 * @license     https://www.gnu.org/licenses/gpl-3.0.html
 */

try {
    $method            = Mage::getModel('paymentsense/moto');
    $code              = $method->getCode();
    $route             = str_replace('_', '/status/', $code);
    $statusUrl         = $this->getBaseUrl() . $route;
    $initialStatusMsg  = $method->isEnabled() ? $this->__('Testing...') : $this->__('Disabled');
    $initialCommonMsg  = $method->isEnabled() ? $this->__('Testing...') : $this->__('Unknown');
    ?>
  <style type="text/css" >
    .paymentsense-section {
      padding: 5px;
      margin-top: 10px;
      margin-bottom: 10px;
    }
    .paymentsense-section .error-text {
      font-weight: bold;
      color: #991015;
    }
    .paymentsense-section .success-text {
      font-weight: bold;
      color: #147908;
    }
    .paymentsense-section .warning-text {
      font-weight: bold;
      color: #333333;
    }
  </style>
  <div class="paymentsense-section">
      <?php

      $script = '';
      if ($method->isEnabled()) {
          $script = "
    <script>
      get" . $code . "Status();

      /**
       * Gets payment method status and connection
       */
      function get" . $code . "Status()
      {
        new Ajax.Request(
          '" . $statusUrl . "',
          {
            method: 'GET',
            onSuccess: showInfo,
            onFailure: showUnknownInfo
          }
        );
      }

      /**
       * Shows the status, connection and settings
       */
      function showInfo(data)
      {
        data = JSON.parse(data.responseText);
        if (data.statusText != null) {
          var statusSpan = document.getElementById('" . $code . "-status');
          var connectionSpan = document.getElementById('" . $code . "-connection');
          var settingsSpan = document.getElementById('" . $code . "-settings');
          var stimeSpan = document.getElementById('" . $code . "-stime');
          statusSpan.innerHTML = data.statusText;
          statusSpan.className = data.statusClassName;
          connectionSpan.innerHTML = data.connectionText;
          connectionSpan.className = data.connectionClassName;
          settingsSpan.innerHTML = data.settingsText;
          settingsSpan.className = data.settingsClassName;
          if (data.stimeText != null) {
            stimeSpan.innerHTML = data.stimeText;
            stimeSpan.className = data.stimeClassName;
            document.getElementById('" . $code . "-stime-div').style.display = \"block\";
          }
        } else {
          showUnknownInfo(data);
        }
      }
      /**
       * Shows an unknown status, connection and settings
       */
      function showUnknownInfo(data)
      {
        var statusSpan = document.getElementById('" . $code . "-status');
        var connectionSpan = document.getElementById('" . $code . "-connection');
        var settingsSpan = document.getElementById('" . $code . "-settings');
        statusSpan.innerHTML = '" . $this->__('Unknown') . "';
        connectionSpan.innerHTML = '" . $this->__('Unknown') . "';
        settingsSpan.innerHTML = '" . $this->__('Unknown') . "';
      }
    </script>
    ";
      }

      echo $script;
      ?>
    <div>
      <span><?php echo $this->__('Payment Method Status:'); ?> </span>
      <span id="<?php echo $code; ?>-status"><?php echo $initialStatusMsg; ?></span>
    </div>
    <div>
      <span><?php echo $this->__('Connection to Gateway Servers:'); ?> </span>
      <span id="<?php echo $code; ?>-connection"><?php echo $initialCommonMsg; ?></span>
    </div>
    <div>
      <span><?php echo $this->__('Gateway Settings:'); ?> </span>
      <span id="<?php echo $code; ?>-settings"><?php echo $initialCommonMsg; ?></span>
    </div>
    <div id="<?php echo $code; ?>-stime-div" style="display: none">
      <span><?php echo $this->__('System Time:'); ?> </span>
      <span id="<?php echo $code; ?>-stime"><?php echo $initialCommonMsg; ?></span>
    </div>
  </div>
    <?php
} catch (\Varien_Exception $e) {
    //Do nothing
}
